name: irgendwas

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # - ./public:/var/www/public:ro
      # - ./src:/var/www/src:ro
      # - ./storage:/var/www/storage:rw
      # - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      # - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - php_logs:/var/log/php-fpm
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - proxynet
      - database
    environment:
      APP_DEBUG: ${APP_DEBUG:-true}
      APP_ENV: ${APP_ENV:-development}
      APP_URL: ${APP_URL:-https://localhost}
      APP_LOCALE: ${APP_LOCALE:-en}
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE:-irgendwas_db}
      DB_USERNAME: ${DB_USERNAME:-irgendjemand}
      DB_PASSWORD: ${DB_PASSWORD:-irgendeinpasswort}
      MAIL_HOST: ${MAIL_HOST:-smtp.gmail.com}
      MAIL_PORT: ${MAIL_PORT:-587}
      MAIL_USERNAME: ${MAIL_USERNAME:-example@gmail.com}
      MAIL_PASSWORD: ${MAIL_PASSWORD:-your_password}
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION:-tls}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS:-noreply@example.com}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME:-Secret Santa}
      CADDY_SITE_ADDRESS: ${CADDY_SITE_ADDRESS:-:80}
      CADDY_AUTO_HTTPS: ${CADDY_AUTO_HTTPS:-off}
      TRUSTED_PROXY_CIDR: ${TRUSTED_PROXY_CIDR:-172.18.0.0/16}
    healthcheck:
      test: ["CMD", "php", "-r", "new PDO('mysql:host=mariadb;dbname=${DB_DATABASE}', '${DB_USERNAME}', '${DB_PASSWORD}');"]
      start_period: 10s
      start_interval: 2s
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-irgendeinrootpasswort}
      MARIADB_DATABASE: ${DB_DATABASE:-irgendwas_db}
      MARIADB_USER: ${DB_USERNAME:-irgendjemand}
      MARIADB_PASSWORD: ${DB_PASSWORD:-irgendeinpasswort}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - database
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 1m
      start_interval: 1s
      interval: 1m
      timeout: 5s
      retries: 3
    restart: unless-stopped

networks:
  proxynet:
    name: proxynet
    driver: bridge
  database:

volumes:
  caddy_data:
  caddy_config:
  mariadb_data:
  php_logs:
