name: irgendwas

services:
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/var/www/public
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      php:
        condition: service_healthy
    networks:
      - web
    environment:
      APP_URL: ${APP_URL:-https://localhost}
    restart: unless-stopped

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - .:/var/www:cached
      - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - vendor_volume:/var/www/vendor
      - php_logs:/var/log/php-fpm
    user: www-data
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - web
      - database
    environment:
      APP_DEBUG: ${APP_DEBUG:-true}
      APP_ENV: ${APP_ENV:-development}
      APP_URL: ${APP_URL:-https://localhost}
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE:-irgendwas_db}
      DB_USERNAME: ${DB_USERNAME:-irgendjemand}
      DB_PASSWORD: ${DB_PASSWORD:-irgendeinpasswort}
      MAIL_HOST: ${MAIL_HOST:-smtp.gmail.com}
      MAIL_PORT: ${MAIL_PORT:-587}
      MAIL_USERNAME: ${MAIL_USERNAME:-example@gmail.com}
      MAIL_PASSWORD: ${MAIL_PASSWORD:-your_password}
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION:-tls}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS:-noreply@example.com}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME:-Secret Santa}
    healthcheck:
      test: ["CMD", "php", "-v"]
      start_period: 5s
      start_interval: 1s
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-irgendeinrootpasswort}
      MARIADB_DATABASE: ${DB_DATABASE:-irgendwas_db}
      MARIADB_USER: ${DB_USERNAME:-irgendjemand}
      MARIADB_PASSWORD: ${DB_PASSWORD:-irgendeinpasswort}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - database
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 1m
      start_interval: 1s
      interval: 1m
      timeout: 5s
      retries: 3
    restart: unless-stopped

networks:
  web:
    name: irgendwas_web_network
  database:
    name: irgendwas_database_network

volumes:
  caddy_data:
    name: irgendwas_caddy_data
  caddy_config:
    name: irgendwas_caddy_config
  mariadb_data:
    name: irgendwas_mariadb_data
  php_logs:
    name: irgendwas_php_logs
  vendor_volume:
    name: irgendwas_vendor_volume